// <auto-generated />
namespace nu1014.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addClub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addClub));
        
        string IMigrationMetadata.Id
        {
            get { return "202310131938393_add Club"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
